### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by jessetane**
Thanks for this module, I have the exact same use case.

As you pointed out in #1, it would be nice to have something a bit more "correct", so I copied in the documentation from the spec(s) and hacked up an implementation. It seems to work (at least for connections from node and chrome) and is about 20x faster. Review / suggestions welcome.

I mentioned it in the docs I added, but I think it would generally be wise to do some other checks to confirm that a given packet even looks like a client hello before using this module. I feel that those checks are out of scope though so I linked to another module (yes, of my authoring...) instead of including them here.

cc @jornane

### CODE REVIEW

**Comment by buschtoens** [comment]
Wow, awesome! I'll have a look through this as soon as I can and add you as a maintainer, if you like. :)

**Comment by buschtoens** [comment]
This is some stellar work! Maybe @jornane and @tellnes (author of [`sni-reader`](https://github.com/tellnes/sni-reader)) would like to weigh in on this before merging?

I don't want to name squat and would be happy to add all you guys as collaborators / maintainers on npm, if you want to.

**Comment by jornane** [comment]
Hi @jessetane! Great work! I've quickly looked over your changes, you've done some serious cleaning.

I'll look into this in more detail shortly.

**Comment by jessetane** [comment]
Ah I had not seen sni-reader! Search fail on my part... it looks like I may have duplicated some of @tellnes efforts... Maybe it is still worth having the standalone guts here?

**Comment by jessetane** [comment]
@buschtoens thanks for adding me as a contributor, happy to help maintain here and on npm where my username should be the same.

**Comment by jornane** [comment]
I've went through your changes. It's good that the code no longer relies on regular expressions so simply find something that "looks like" a domain. However, your code lacks some checks that @tellnes sni-reader has. For example, it's possible to crash your code in the `var sessionIdLength = data[pos];` line by having too few bytes in data.

As @jessetane mentioned in the documentation, this problem can be solved by checking the data first. But I think it's a bit dirty to have some of the checking in the `sni`-library and other checking in his own `is-tls-client-hello`-library.

Personally, I prefer @tellnes his approach, where the library takes care of everything that's related to SNI-parsing, such as socket handling and validation. You can look at https://github.com/jornane/node-snip to see how I use sni-reader today.

I will leave the merge decision to @buschtoens.

**Comment by jessetane** [comment]
@jornane thanks for the review. I still see the function of verifying the record and extracting the sni as separate things. And actually, if you look at the sni-reader source, you can see that these functions are split up internally:
https://github.com/tellnes/sni-reader/blob/master/index.js#L52-L74
https://github.com/tellnes/sni-reader/blob/master/index.js#L76-L172

**Comment by jessetane** [comment]
It's definitely nice to have the sni-reader package that "does all the things", but having access to the little lego pieces is nice too (I don't need the stream handling stuff personally). Maybe not worth the effort, but maybe it would make sense to to compose sni-reader out of smaller modules?

**Comment by jessetane** [comment]
@jornane also you are right about the sessionid length check - I added a commit to fix, thanks!

**Comment by jessetane** [comment]
@buschtoens any objection to me going ahead and merging this?

**Comment by buschtoens** [comment]
@jessetane Nope, absolutely in favor! I also prefer the Lego approach. :wink:

**Comment by jessetane** [comment]
This isn't really a feature addition or breaking change, but I think we can probably bump to 1.0.0 for release - if you add me on npm I can go ahead and publish as well.

**Comment by buschtoens** [comment]
You should already be added. :+1:

**Comment by jessetane** [comment]
done and done, thanks!

**Comment by buschtoens** [comment]
Nah, thank _you_. :smile:

**Comment by tellnes** [comment]
Hi. Thanks for mentioning me.

This implementation will still fail if the input is less bytes than where the SNI extension is found. That is the reason I'm handling the stream stuff in `sni-reader`. I'm first reading five bytes. The last two of them tells me how much more I need to read to be guaranteed to read enough.

Yes, the first data blob you receive from the stream api on the socket will probably include everything you need because it will probably be in the first tcp packet, but that is an implementation detail and not something the api guarantees.

Other that that, it looks great.

**Pull request merged**
